export const USER_LOGIN = 'USER_LOGIN';
export const TOKEN_MY_LIFE = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMWRlNDNiMjY5NGI4MDAxZDU5YmE2NSIsImlhdCI6MTY0NzQ4NDMzOSwiZXhwIjoxNjQ3NDg3OTM5fQ.xRBeDYWjlU2ejWg2fmT2CmlFNIEJfD8tW60Su6P-_uQ';
export const DOMAIN_MY_LIFE = 'https://ml365-d.devops-sup.tech';
